import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Providers from '@/lib/Provider'
import Navbar from '@/components/Navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ecommerce Market',
  description: 'Generated by create next app',
}

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </ClerkProvider>
      </body>
    </html>
  )
}

export default RootLayout
